(define L1 (list 2 3 4 5 1))
(define L2 (list 2 3 4 5 1))
(define L3 (list 2 3 4 5 1))
(define L4 (list 2 3 4 5 1))

(define (fx)
  (if (equal? L1 L2)
      (if (equal? L1 L3)
          (if (equal? L1 L4)
              (display "Las listas son iguales ") 
              (display "Las listas no son iguales ") 
          )
       )
   )
)
(fx)


(define (fx2)
  (if (equal? (equal? L1 L2) (equal? L3 L4))
          (display " Las listas son iguales") 
          (display " Las listas no son iguales") 
  )
)
(fx2)